version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: traknor
      POSTGRES_USER: traknor
      POSTGRES_PASSWORD: traknor123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgresql://traknor:traknor123@postgres:5432/traknor
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

volumes:
  postgres_data: