# Generated by Django 5.0.1 on 2025-09-08 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "tag",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SPLIT", "Split"),
                            ("CENTRAL", "Central"),
                            ("VRF", "VRF"),
                            ("CHILLER", "Chiller"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FUNCTIONING", "Funcionando"),
                            ("MAINTENANCE", "Em Manutenção"),
                            ("STOPPED", "Parado"),
                            ("DECOMMISSIONED", "Descomissionado"),
                        ],
                        default="FUNCTIONING",
                        max_length=20,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("install_date", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("total_operating_hours", models.PositiveIntegerField(default=0)),
                (
                    "energy_consumption",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="kWh", max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="companies.company",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="companies.sector",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="companies.subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["code"],
            },
        ),
    ]
