/**
 * Definições de ícones disponíveis para o Card KPI
 */
import {
  Activity,
  Thermometer,
  Droplets,
  Wind,
  Zap,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Battery,
  BatteryCharging,
  BatteryLow,
  BatteryFull,
  Wifi,
  WifiOff,
  Signal,
  SignalHigh,
  SignalLow,
  Heart,
  HeartPulse,
  Cpu,
  HardDrive,
  Monitor,
  Gauge,
  Clock,
  Timer,
  Hourglass,
  Server,
  Database,
  Users,
  User,
  UserCheck,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  AlertCircle,
  AlertOctagon,
  Bell,
  BellRing,
  TrendingUp,
  TrendingDown,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  BarChart3,
  BarChart2,
  BarChart,
  PieChart,
  LineChart,
  AreaChart,
  Percent,
  DollarSign,
  Euro,
  Coins,
  CreditCard,
  Wallet,
  ShoppingCart,
  Package,
  Truck,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Home,
  Building,
  Building2,
  Factory,
  Warehouse,
  Wrench,
  Settings,
  Cog,
  Hammer,
  Plug,
  Power,
  PowerOff,
  ToggleLeft,
  ToggleRight,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  Eye,
  EyeOff,
  Camera,
  Video,
  Mic,
  Volume2,
  VolumeX,
  Phone,
  Mail,
  Send,
  MessageSquare,
  FileText,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Star,
  StarHalf,
  Award,
  Trophy,
  Target,
  Crosshair,
  Focus,
  Layers,
  Grid,
  Layout,
  Boxes,
  Box,
  Archive,
  Folder,
  File,
  Download,
  Upload,
  RefreshCw,
  RotateCcw,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  LucideIcon
} from 'lucide-react';

// Mapa de ícones disponíveis para o Card KPI
export const kpiIconMap: Record<string, LucideIcon> = {
  // Atividade e Monitoramento
  'activity': Activity,
  'heart-pulse': HeartPulse,
  'gauge': Gauge,
  'target': Target,
  'crosshair': Crosshair,
  'focus': Focus,
  
  // Clima e Ambiente
  'thermometer': Thermometer,
  'droplets': Droplets,
  'wind': Wind,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-lightning': CloudLightning,
  'snowflake': Snowflake,
  
  // Energia e Elétrica
  'zap': Zap,
  'flame': Flame,
  'plug': Plug,
  'power': Power,
  'power-off': PowerOff,
  'battery': Battery,
  'battery-charging': BatteryCharging,
  'battery-low': BatteryLow,
  'battery-full': BatteryFull,
  
  // Conectividade
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'signal': Signal,
  'signal-high': SignalHigh,
  'signal-low': SignalLow,
  'globe': Globe,
  
  // Saúde e Status
  'heart': Heart,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'bell': Bell,
  'bell-ring': BellRing,
  'shield': Shield,
  'shield-check': ShieldCheck,
  
  // Tendências e Gráficos
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'bar-chart': BarChart3,
  'bar-chart-2': BarChart2,
  'bar-chart-simple': BarChart,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  'area-chart': AreaChart,
  'percent': Percent,
  
  // Tempo
  'clock': Clock,
  'timer': Timer,
  'hourglass': Hourglass,
  'calendar': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  
  // Hardware e TI
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'monitor': Monitor,
  'server': Server,
  'database': Database,
  
  // Usuários
  'users': Users,
  'user': User,
  'user-check': UserCheck,
  
  // Finanças
  'dollar-sign': DollarSign,
  'euro': Euro,
  'coins': Coins,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'shopping-cart': ShoppingCart,
  
  // Logística
  'package': Package,
  'truck': Truck,
  'map-pin': MapPin,
  'navigation': Navigation,
  'compass': Compass,
  
  // Construção e Indústria
  'home': Home,
  'building': Building,
  'building-2': Building2,
  'factory': Factory,
  'warehouse': Warehouse,
  
  // Ferramentas e Configuração
  'wrench': Wrench,
  'settings': Settings,
  'cog': Cog,
  'hammer': Hammer,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  
  // Segurança
  'lock': Lock,
  'unlock': Unlock,
  'eye': Eye,
  'eye-off': EyeOff,
  
  // Mídia e Comunicação
  'camera': Camera,
  'video': Video,
  'mic': Mic,
  'volume': Volume2,
  'volume-x': VolumeX,
  'phone': Phone,
  'mail': Mail,
  'send': Send,
  'message': MessageSquare,
  
  // Documentos
  'file-text': FileText,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  
  // Conquistas
  'star': Star,
  'star-half': StarHalf,
  'award': Award,
  'trophy': Trophy,
  
  // Organização
  'layers': Layers,
  'grid': Grid,
  'layout': Layout,
  'boxes': Boxes,
  'box': Box,
  'archive': Archive,
  'folder': Folder,
  'file': File,
  
  // Ações
  'download': Download,
  'upload': Upload,
  'refresh': RefreshCw,
  'rotate': RotateCcw,
  'play': Play,
  'pause': Pause,
  
  // Formas
  'square': Square,
  'circle': Circle,
  'triangle': Triangle,
  'hexagon': Hexagon,
  'octagon': Octagon,
};

// Lista de ícones para seleção no config (agrupados por categoria)
export const kpiIconOptions = [
  // Atividade e Monitoramento
  { value: 'activity', label: 'Atividade' },
  { value: 'heart-pulse', label: 'Pulso' },
  { value: 'gauge', label: 'Medidor' },
  { value: 'target', label: 'Alvo' },
  { value: 'crosshair', label: 'Mira' },
  { value: 'focus', label: 'Foco' },
  
  // Clima e Ambiente
  { value: 'thermometer', label: 'Temperatura' },
  { value: 'droplets', label: 'Umidade' },
  { value: 'wind', label: 'Vento' },
  { value: 'sun', label: 'Sol' },
  { value: 'moon', label: 'Lua' },
  { value: 'cloud', label: 'Nuvem' },
  { value: 'cloud-rain', label: 'Chuva' },
  { value: 'cloud-snow', label: 'Neve' },
  { value: 'cloud-lightning', label: 'Raio' },
  { value: 'snowflake', label: 'Floco de Neve' },
  
  // Energia e Elétrica
  { value: 'zap', label: 'Energia' },
  { value: 'flame', label: 'Chama' },
  { value: 'plug', label: 'Tomada' },
  { value: 'power', label: 'Ligar' },
  { value: 'power-off', label: 'Desligar' },
  { value: 'battery', label: 'Bateria' },
  { value: 'battery-charging', label: 'Carregando' },
  { value: 'battery-low', label: 'Bateria Baixa' },
  { value: 'battery-full', label: 'Bateria Cheia' },
  
  // Conectividade
  { value: 'wifi', label: 'WiFi' },
  { value: 'wifi-off', label: 'WiFi Off' },
  { value: 'signal', label: 'Sinal' },
  { value: 'signal-high', label: 'Sinal Alto' },
  { value: 'signal-low', label: 'Sinal Baixo' },
  { value: 'globe', label: 'Global' },
  
  // Saúde e Status
  { value: 'heart', label: 'Coração' },
  { value: 'check-circle', label: 'Verificado' },
  { value: 'check-circle-2', label: 'Confirmado' },
  { value: 'x-circle', label: 'Erro' },
  { value: 'alert-triangle', label: 'Alerta' },
  { value: 'alert-circle', label: 'Atenção' },
  { value: 'alert-octagon', label: 'Perigo' },
  { value: 'bell', label: 'Sino' },
  { value: 'bell-ring', label: 'Notificação' },
  { value: 'shield', label: 'Escudo' },
  { value: 'shield-check', label: 'Protegido' },
  
  // Tendências e Gráficos
  { value: 'trending-up', label: 'Subindo' },
  { value: 'trending-down', label: 'Descendo' },
  { value: 'arrow-up', label: 'Seta Cima' },
  { value: 'arrow-down', label: 'Seta Baixo' },
  { value: 'arrow-up-right', label: 'Seta Diagonal ↗' },
  { value: 'arrow-down-right', label: 'Seta Diagonal ↘' },
  { value: 'bar-chart', label: 'Gráfico Barras' },
  { value: 'bar-chart-2', label: 'Gráfico Barras 2' },
  { value: 'bar-chart-simple', label: 'Barras Simples' },
  { value: 'pie-chart', label: 'Gráfico Pizza' },
  { value: 'line-chart', label: 'Gráfico Linha' },
  { value: 'area-chart', label: 'Gráfico Área' },
  { value: 'percent', label: 'Percentual' },
  
  // Tempo
  { value: 'clock', label: 'Relógio' },
  { value: 'timer', label: 'Timer' },
  { value: 'hourglass', label: 'Ampulheta' },
  { value: 'calendar', label: 'Calendário' },
  { value: 'calendar-check', label: 'Agendado' },
  { value: 'calendar-clock', label: 'Prazo' },
  
  // Hardware e TI
  { value: 'cpu', label: 'CPU' },
  { value: 'hard-drive', label: 'HD' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'server', label: 'Servidor' },
  { value: 'database', label: 'Banco de Dados' },
  
  // Usuários
  { value: 'users', label: 'Usuários' },
  { value: 'user', label: 'Usuário' },
  { value: 'user-check', label: 'Usuário Ativo' },
  
  // Finanças
  { value: 'dollar-sign', label: 'Dólar' },
  { value: 'euro', label: 'Euro' },
  { value: 'coins', label: 'Moedas' },
  { value: 'credit-card', label: 'Cartão' },
  { value: 'wallet', label: 'Carteira' },
  { value: 'shopping-cart', label: 'Carrinho' },
  
  // Logística
  { value: 'package', label: 'Pacote' },
  { value: 'truck', label: 'Caminhão' },
  { value: 'map-pin', label: 'Localização' },
  { value: 'navigation', label: 'Navegação' },
  { value: 'compass', label: 'Bússola' },
  
  // Construção e Indústria
  { value: 'home', label: 'Casa' },
  { value: 'building', label: 'Prédio' },
  { value: 'building-2', label: 'Edifício' },
  { value: 'factory', label: 'Fábrica' },
  { value: 'warehouse', label: 'Armazém' },
  
  // Ferramentas e Configuração
  { value: 'wrench', label: 'Chave' },
  { value: 'settings', label: 'Configurações' },
  { value: 'cog', label: 'Engrenagem' },
  { value: 'hammer', label: 'Martelo' },
  { value: 'toggle-left', label: 'Toggle Off' },
  { value: 'toggle-right', label: 'Toggle On' },
  
  // Segurança
  { value: 'lock', label: 'Bloqueado' },
  { value: 'unlock', label: 'Desbloqueado' },
  { value: 'eye', label: 'Visível' },
  { value: 'eye-off', label: 'Oculto' },
  
  // Mídia e Comunicação
  { value: 'camera', label: 'Câmera' },
  { value: 'video', label: 'Vídeo' },
  { value: 'mic', label: 'Microfone' },
  { value: 'volume', label: 'Volume' },
  { value: 'volume-x', label: 'Mudo' },
  { value: 'phone', label: 'Telefone' },
  { value: 'mail', label: 'E-mail' },
  { value: 'send', label: 'Enviar' },
  { value: 'message', label: 'Mensagem' },
  
  // Documentos
  { value: 'file-text', label: 'Documento' },
  { value: 'clipboard', label: 'Prancheta' },
  { value: 'clipboard-check', label: 'Concluído' },
  { value: 'clipboard-list', label: 'Lista' },
  
  // Conquistas
  { value: 'star', label: 'Estrela' },
  { value: 'star-half', label: 'Meia Estrela' },
  { value: 'award', label: 'Prêmio' },
  { value: 'trophy', label: 'Troféu' },
  
  // Organização
  { value: 'layers', label: 'Camadas' },
  { value: 'grid', label: 'Grade' },
  { value: 'layout', label: 'Layout' },
  { value: 'boxes', label: 'Caixas' },
  { value: 'box', label: 'Caixa' },
  { value: 'archive', label: 'Arquivo' },
  { value: 'folder', label: 'Pasta' },
  { value: 'file', label: 'Arquivo' },
  
  // Ações
  { value: 'download', label: 'Download' },
  { value: 'upload', label: 'Upload' },
  { value: 'refresh', label: 'Atualizar' },
  { value: 'rotate', label: 'Girar' },
  { value: 'play', label: 'Play' },
  { value: 'pause', label: 'Pausar' },
  
  // Formas
  { value: 'square', label: 'Quadrado' },
  { value: 'circle', label: 'Círculo' },
  { value: 'triangle', label: 'Triângulo' },
  { value: 'hexagon', label: 'Hexágono' },
  { value: 'octagon', label: 'Octógono' },
];
